\documentclass{beamer}
\usepackage{amsmath, amsthm}
\usepackage{parskip, microtype, graphicx, caption}

\frenchspacing  % i likes it

<<message = FALSE, echo = FALSE, warning = FALSE>>=
require(knitr)
require(xtable)
require(ggplot2)
require(reshape2)
require(GGally)

opts_chunk$set(warning = FALSE, echo = FALSE, message = FALSE,
               highlight = TRUE, background = 'white',
               fig.height = 3, fig.width = 4
               , eval = FALSE
               )


source('../src/plotting_functions.r')
#load('../src/turtle_analysis.r')
@

<<>>=
# need to format all the map data so it plays nicely
map <- map_data('state')
st <- c('california', 'oregon', 'washington')
map <- map[map$region == st, ]

labs <- Map(function(x, n) x[, n],
            x = turtle.train, n = names(turtle.train))
@

\title{How cryptic is cryptic diversity? Machine learning approaches to fine scale variation in the morphology of \textit{Emys marmorata}.}
\author[shortname]{Peter D Smits\inst{1}, 
                   Kenneth D Angielczyk\inst{2}, 
                   James F Parham\inst{3}}
\institute[shortinst]{\inst{1} Committee on Evolution Biology, University of Chicago,
                      \inst{2} Department of Geology, Field Museum of Natural History,
                      \inst{3} Department of Geological Sciences, California State University -- Fullerton}

\begin{document}

\begin{frame}
  \maketitle
\end{frame}


\section{Introduction}
\begin{frame}
  \frametitle{Cryptic diversity}
  % image of example taxa that are morphologically identical and are only differentiated via genetic means
\end{frame}

\begin{frame}
  \frametitle{\textit{Emys marmorata}}
  % picture of a turtle
  % this is the study system
  % a little natural history
  % a little biogeography
  \begin{figure}[h]
    \centering
    \captionsetup{justification = raggedleft, slc = off}
    \includegraphics[width = 0.8\textwidth, keepaspectratio = true]{figure/turtle}
    \caption*{wikimedia}
    \label{fig:turtle}
  \end{figure}
\end{frame}

\begin{frame}
  \frametitle{Morphological hypotheses}
\end{frame}

\begin{frame}
  \frametitle{Phylogenetic hypotheses}

  Number of subspecies and where they occur.
  % images of the different phylobiogeographic hypotheses from the different spinks papers
\end{frame}


\section{Methods}
\begin{frame}
  \frametitle{Methods: morphometrics}
  \begin{columns}
    \begin{column}{0.5\textwidth}
      \begin{itemize}
        %\item \Sexpr{nrow(turtle.adult)} adult individuals
        \item plastral (``belly'') shape
        \item landmarks averaged across bilat axis
        \item total 13 landmarks, 7 on bilat axis, 6 off
        \item geographic information known/inferred
      \end{itemize}
    \end{column}
    \begin{column}{0.5\textwidth}
      \centering
      \includegraphics[width = \textwidth, keepaspectratio = true]{figure/plastra}
    \end{column}
  \end{columns}
\end{frame}

\begin{frame}
  \frametitle{Methods: unsupervised learning}

  Fancy way of saying clustering or density estimation.

  Partitioning around mediods (PAM) compared with ``gap'' statistic.

  (dissimilarity based) Evidence accumulation clustering
\end{frame}

\begin{frame}
  \frametitle{Methods: supervised learning}

  Fancy way of saying classification and regression.

  Here, features (principal components) predict class (subspecific assignment).

  Multnomial logistic regression

  Random forests
\end{frame}

\begin{frame}
  \frametitle{Methods: model training and selection}
  Unknown appropriate number of features to ``best'' predict class. Want to minimize false positive, while maximizing true positive.

  Split data set, 75-25, training and testing.

  Tuning parameters via grid-search. Uncertainty via 10-fold cross-validation.

  Multinomial logistic model selected via min AICc. Random forest model via max AUC ROC.

\end{frame}
%\begin{frame}
%  \frametitle{Methods: ROC}
%\end{frame}


\section{Results}
\begin{frame}
  \frametitle{Results: mophometrics}
<<gm, eval = FALSE>>=
morph <- ggpairs(turtle.adult, columns = c(1:3),
                 upper = 'blank')
fits <- procGPA(turtle.land.adult)
land <- mshape.plot(fits, all.points = TRUE)
morph <- putPlot(morph, land, 1, 3)
morph
@
\end{frame}

\begin{frame}
  \frametitle{Results: gap clustering}
<<gap, eval = FALSE>>=
gap <- gap.plot(tadult.gap)
gap
@
\end{frame}

\begin{frame}
  \frametitle{Results: d-EAC}

\end{frame}

% model selection is unnecessary because of time constraints
\begin{frame}
  \frametitle{Results: multinomial logistic regression}

\end{frame}

\begin{frame}
  \frametitle{Results: random forests}
  % plot the ROC curves
  % four facets, multiple lines
\end{frame}


\section{Discussion}
\begin{frame}
  \frametitle{Best classification scheme}
\end{frame}

\begin{frame}
  \frametitle{Future}
\end{frame}

\begin{frame}
  \frametitle{Acknowledgements}
  \begin{columns}
    \begin{column}{0.5\textwidth}
      \begin{itemize}
        \item Ben Frable, Dallas Krentzel, Michael Foote
        \item COLLECTIONS
      \end{itemize}
    \end{column}
    \begin{column}{0.5\textwidth}
      \includegraphics[height = 0.25\textheight, keepaspectratio = true]{figure/chicago} \\
      \includegraphics[height = 0.25\textheight, width = \textwidth, keepaspectratio = true]{figure/field} \\
      \includegraphics[height = 0.25\textheight, keepaspectratio = true]{figure/csu}
    \end{column}
  \end{columns}
\end{frame}
\end{document}
