\documentclass{beamer}
\usepackage{amsmath, amsthm}
\usepackage{parskip, microtype, graphicx, caption, multirow, subcaption}

\frenchspacing  % i likes it

<<message = FALSE, echo = FALSE, warning = FALSE>>=
require(knitr)
require(xtable)
require(grid)
require(ggplot2)
require(reshape2)
require(GGally)
require(scales)
require(boot)

require(shapes)
require(geomorph)

opts_chunk$set(warning = FALSE, echo = FALSE, message = FALSE,
               highlight = TRUE, background = 'white',
               fig.height = 3, fig.width = 4
               , eval = TRUE
               )

theme_set(theme_bw())
cbp <- c(#'#999999', 
         '#E69F00', '#56B4E9', '#009E73', 
         '#F0E442', '#0072B2', '#D55E00', '#CC79A7')

source('../src/support_functions.r')
source('../src/plotting_functions.r')
load('../data/turtle_analysis.RData')
load('../data/turtle_gen.RData')
@

<<>>=
# need to format all the map data so it plays nicely
map <- map_data('state')
st <- c('california'
        , 'oregon'
        #, 'washington'
        )
map <- map[map$region == st, ]

labs <- Map(function(x, n) x[, n],
            x = adult.train, n = names(adult.train))

turtle.adult$long[which(turtle.adult$long > -100)] <- turtle.adult$long[which(turtle.adult$long > -100)] - 100

adult.train$spinks$long[which(adult.train$spinks$long > -100)] <- adult.train$spinks$long[which(adult.train$spinks$long > -100)] - 100

@

\title{How cryptic is cryptic diversity? \newline Machine learning approaches to fine scale variation in the morphology of \textit{Emys marmorata}.}
\author[shortname]{Peter D Smits\inst{1}, 
                   Kenneth D Angielczyk\inst{2}, 
                   James F Parham\inst{3}}
\institute[shortinst]{\inst{1} Committee on Evolution Biology, University of Chicago,
                      \inst{2} Department of Geology, Field Museum of Natural History,
                      \inst{3} Department of Geological Sciences, California State University -- Fullerton}

\begin{document}

\begin{frame}
  \maketitle
\end{frame}


\section{Introduction}
\begin{frame}
  \frametitle{Cryptic diversity}
  % image of example taxa that are morphologically identical and are only differentiated via genetic means
  %
  Crytic species are species delimitated via molecular means. Taxa were not/cannot be identified via morphology.

  How much of cryptic diversity is just a function of sample size and/or method?

\end{frame}

\begin{frame}
  \frametitle{\textit{Emys marmorata}}
  % picture of a turtle
  % this is the study system
  % a little natural history
  % a little biogeography
  \begin{figure}[h]
    \centering
    \captionsetup{justification = raggedleft, slc = off}
    \includegraphics[width = 0.8\textwidth, keepaspectratio = true]{figure/turtle}
    \caption*{wikimedia}
    \label{fig:turtle}
  \end{figure}
\end{frame}

\begin{frame}
  \frametitle{Morphological hypothesis}

  \begin{figure}[h]
    \centering
    \captionsetup{justification = raggedleft, slc = off}
    \includegraphics[height = 0.8\textheight, keepaspectratio = true]{figure/seeliger}
    \caption*{\scriptsize{Seeliger 1945 \textit{Copeia}}}
    \label{fig:seeliger}
  \end{figure}
  % basic north/south stuff
  % earlier work by the masters student

\end{frame}

\begin{frame}
  \frametitle{Phylogenetic hypotheses}

  \begin{figure}[h]
    \centering
    \captionsetup{justification = raggedleft, slc = off}
    \includegraphics[height = 0.8\textheight, keepaspectratio = true]{figure/spinks10}
    \caption*{\scriptsize{Spinks \textit{et al.} 2010 \textit{Molec. Ecol}}}
    \label{fig:spinks}
  \end{figure}
  % Number of subspecies and where they occur.
  % images of the different phylobiogeographic hypotheses from the different spinks papers
 
\end{frame}


\section{Methods}
\begin{frame}
  \frametitle{Methods: morphometrics}
  \begin{columns}
    \begin{column}{0.5\textwidth}
      \begin{itemize}
        \item \Sexpr{nrow(turtle.adult)} adult individuals
        \item plastral (``belly'') shape
        \item landmarks averaged across bilat axis
        \item total 13 landmarks, 7 on bilat axis, 6 off
        \item geographic information known/inferred
      \end{itemize}
    \end{column}
    \begin{column}{0.5\textwidth}
      \begin{figure}[h]
        \centering
        \captionsetup{justification = raggedleft, slc = off}
        \includegraphics[width = \textwidth, keepaspectratio = true]{figure/plastra}
        \caption*{\scriptsize{Angielczyk \textit{et al.} 2011 \textit{Evolution}}}
        \label{fig:plast}
      \end{figure}
    \end{column}
  \end{columns}
\end{frame}

\begin{frame}
  \frametitle{Unsupervised learning}

  Fancy way of saying clustering or density estimation.

  Partitioning around mediods (PAM) compared with ``gap'' statistic.

  Analogous to \textit{k}-means clustering, a divisive clustering algorithm.

  Minimize sum of dissimilarities between points and medoids.

  ``Gap'' is analogous to goodness-of-clustering.
  
\end{frame}

\begin{frame}
  \frametitle{Supervised learning}

  Fancy way of saying classification (and regression).

  Features (principal components) predict class (subspecific assignment).

  Multinomial logistic regression and random forests.

\end{frame}

\begin{frame}
  \frametitle{Model training and selection}

  \begin{itemize}
    \item split into training and testing sets, 75-25.
    \item tuning parameters via grid-search
    \item uncertainty via 10-fold CV
    \item model selection
      \begin{itemize}
        \item multinomial logistic regression: min AICc
        \item random forest: max ROC
      \end{itemize}
  \end{itemize}

\end{frame}

\begin{frame}
  \frametitle{ROC and confusion matrices}

  \begin{center}
    \begin{tabular}[c]{ p{2cm} c | p{2cm} | p{2cm} |}
      \cline{3-4} 
      & & \multicolumn{2}{ c |}{Predicted class} \\ \cline{3-4}
      & & 1 & 0 \\ \hline
      \multicolumn{1}{| c |}{\multirow{2}{*}{Actual class}}
      & 1 & TRUE \newline POSITIVE & FALSE \newline NEGATIVE \\ \cline{2-4}
      \multicolumn{1}{| c |}{} & 0 & FALSE \newline POSITIVE & TRUE \newline NEGATIVE \\
      \hline
    \end{tabular}
  \end{center}

\end{frame}

\begin{frame}
  \frametitle{ROC}
  \begin{columns}
    \begin{column}{0.4\textwidth}
      \begin{itemize}
        \item true positive rate or sensitivity: \(\frac{TP}{TP + FN}\)
        \item false positive rate or \newline 1 - specificity: \(\frac{FP}{FP + TN}\)
        \item multiclass, all-against one (Hand and Till 2001 \textit{Machine Learning})
      \end{itemize}
    \end{column}
    \begin{column}{0.6\textwidth}
      \begin{figure}[h]
        \centering
        \captionsetup{justification = raggedleft, slc = off}
        \includegraphics[width = \textwidth, keepaspectratio = true]{figure/wiki_roc}
        \caption*{\scriptsize{wikimedia}}
        \label{fig:roc}
      \end{figure}
    \end{column}
  \end{columns}

\end{frame}


\section{Results}
\begin{frame}[fragile]
  \frametitle{Results: mophometrics}
<<gm, results = 'hide', fig.width = 3.5, fig.height = 3.5, eval = TRUE>>=
morph <- ggpairs(turtle.adult, columns = c(1:3),
                 upper = 'blank',
                 params = c(LabelSize = 2, gridLabelSize = 2, size = 1))
fits <- procGPA(turtle.land.adult)
links <- c(1:7, 13:8)
land <- mshape.plot(fits, links = links)
land <- land + coord_equal()
morph <- putPlot(morph, land, 1, 3)
morph
@

\end{frame}

\begin{frame}[fragile]
  \frametitle{Results: gap clustering}
<<gap, fig.width = 4, fig.height = 3,  eval = TRUE>>=
gap <- gap.plot(tadult.gap)
gap <- gap + theme(axis.title = element_text(size = 7.5),
                   axis.text = element_text(size = 6))
gap
@
\end{frame}

\begin{frame}
  \frametitle{Second best cluster}
<<>>=
gap.second <- pam(as.dist(turtle.adult.dist), k = 2)
gap.map <- map.plot(data = turtle.adult,
                    label = gap.second$clustering,
                    map = map)
gap.map <- gap.map + scale_colour_manual(values = cbp)
gap.map <- gap.map + theme(legend.position = 'none',
                           legend.text = element_text(size = 5),
                           axis.title = element_text(size = 8),
                           axis.text = element_text(size = 5))
gap.map
@

\end{frame}


\begin{frame}[fragile]
  \frametitle{Model selection via ROC}
<<roc, eval = TRUE>>=
rf.rocs <- lapply(trf.a, function(x) {
                  rr <- x$results$ROC
                  rr})
rf.rocs <- ldply(rf.rocs)
multi.rocs <- lapply(tm.a, function(x) {
                     lapply(x, function(y) {
                            rr <- max(y$results$ROC)
                            rr})})
multi.rocs <- ldply(lapply(lapply(multi.rocs, ldply), t))

names(rf.rocs) <- names(multi.rocs) 
roc.mod <- rbind(rf.rocs, multi.rocs)
mod.names <- c(rep('rf', nrow(rf.rocs)), rep('multi', nrow(multi.rocs)))
roc.mod <- cbind(mod.names, roc.mod)
roc.mod <- melt(roc.mod)
roc.mod$variable <- as.numeric(roc.mod$variable)

ggroc <- ggplot(roc.mod, aes(x = variable, y = value, color = mod.names))
ggroc <- ggroc + geom_line()
ggroc <- ggroc + scale_x_continuous(breaks = seq(max(roc.mod$variable)))
ggroc <- ggroc + scale_color_manual(labels = c('multinomial', 
                                                 'random forest'),
                                      values = cbp)
ggroc <- ggroc + theme(legend.title = element_blank(),
                       legend.position = 'right',
                       legend.margin = unit(0, 'cm'),
                       legend.text = element_text(size = 5),
                       axis.title = element_text(size = 8),
                       axis.text = element_text(size = 5))
ggroc <- ggroc + labs(x = '# of features', y = 'AUC ROC')
ggroc <- ggroc + facet_wrap(~.id)
ggroc
@

\end{frame}

%\begin{frame}
%  \frametitle{Are the AUC ROC values meaningful?}
%\end{frame}

\begin{frame}
  \frametitle{Generalize using best random forest model}
<<>>=
oo <- Reduce(cbind, Map(function(x) x$t, rr))
colnames(oo) <- groups
dd <- melt(oo)
gdist <- ggplot(dd, aes(x = value, fill = X2)) + geom_density(alpha = 0.5,
                                                              size = 0.1)
gdist <- gdist + theme(legend.position = 'none',
                       #legend.title = element_blank(),
                       #legend.margin = unit(0, 'cm'),
                       #legend.text = element_blank(),
                       axis.title = element_text(size = 8),
                       axis.text = element_text(size = 5))
gdist <- gdist + scale_fill_manual(name = '', values = cbp)

gdist
@

\end{frame}

\begin{frame}
  \frametitle{Best classification scheme via RF model results}
<<>>=
gg <- class.map(adult.train$spinks, adult.test$spinks, labs$spinks, 
                trf.a.analysis$class$spinks$pred, map)
gg <- gg + scale_colour_manual(name = '', values = cbp)
gg <- gg + theme(legend.position = 'none',
                 #legend.margin = unit(0, 'cm'),
                 #legend.text = element_text(size = 5),
                 axis.title = element_text(size = 8),
                 axis.text = element_text(size = 5))
gg
@

\end{frame}

\begin{frame}[fragile]
  \frametitle{Mean shape of classes}

<<fig.width = 3.75, fig.height = 3.75>>=
# get mean of each class

mt <- mshape(turtle.land.adult)

spi <- turtle.adult$spinks
wspi <- lapply(levels(spi), function(x, y) which(y == x), y = spi)
mspi <- lapply(wspi, function(x, y) mshape(y[, , x]), y = turtle.land.adult)
par(mfrow = c(2, 2), mar = c(0, 0, 1, 1) + 0.1, oma = c(5, 4, 0, 0) + 0.1,
    xaxt = 'n', yaxt = 'n')
mins <- lapply(mspi, function(x) min(x[, 2]))
mins <- min(unlist(mins))
lmat <- cbind(links, c(links[-1], links[1]))
mapply(function(x, m, n) {
      #tpsgrid(x, m, mag = 2, ext = 0, cex = 2)
      plotRefToTarget(M1 = m, M2 = x, mag = 2, links = lmat)
      title(main = paste(n))}, x = mspi, n = levels(spi),
      MoreArgs = list(m = mt), SIMPLIFY = FALSE)
par(mfrow = c(1, 1))

multi.mean <- multishape.plot(mspi, links = links)
@

\end{frame}

\begin{frame}[fragile]
  \frametitle{Variable importance of random forest model}
  % ggpairs from the best random forest model
<<imp, fig.width = 3.5, fig.height = 3.5, eval = TRUE>>=
most.imp <- trf.a$spinks$optVariables
ww <- 'spinks'
ggimp <- ggpairs(turtle.adult,
                 columns = c(most.imp[1:3], ww), 
                 colour = 'spinks',
                 upper = 'blank',
                 params = c(LabelSize = 2, gridLabelSize = 2, size = 1))

#putPlot
ggimp
@
\end{frame}

\begin{frame}
  \frametitle{Shape across PC3}

<<fig.width = 5>>=

fst.max <- which.max(turtle.adult[, most.imp[1]])
fst.min <- which.min(turtle.adult[, most.imp[1]])

snd.max <- which.max(turtle.adult[, most.imp[2]])
snd.min <- which.min(turtle.adult[, most.imp[2]])

#par(mfrow = c(1, 2), mar = c(0, 0, 1, 1) + 0.1, oma = c(5, 4, 0, 0) + 0.1,
#    xaxt = 'n', yaxt = 'n', bty = 'n')
#tpsgrid(turtle.land.adult[, , fst.min], mt, mag = 2)
#plotRefToTarget(M1 = mt, M2 = turtle.land.adult[, , fst.min])
#title(main = 'min observed')
#tpsgrid(turtle.land.adult[, , fst.max], mt, mag = 2)
#plotRefToTarget(M1 = mt, M2 = turtle.land.adult[, , fst.max])
#title(main = 'max observed')
#par(mfrow = c(1, 1))


ex.lab <- function(var, value) {
  value <- as.character(value)
  if(var == 'lab') {
    value[value == '1'] <- 'min'
    value[value == '2'] <- 'mean'
    value[value == '3'] <- 'max'
  }
  return(value)
}

fst.mean <- multishape.plot(list(turtle.land.adult[, , fst.min], 
                                 mt,
                                 turtle.land.adult[, , fst.max]), 
                            links = links,
                            labeller = ex.lab)
fst.mean <- fst.mean + theme(axis.title = element_blank(),
                             axis.text = element_text(size = 4))
fst.mean <- fst.mean + coord_equal()
fst.mean
@

\end{frame}

\begin{frame}
  \frametitle{Shape across PC8}
<<fig.width = 5>>=
#par(mfrow = c(1, 2), mar = c(0, 0, 1, 1) + 0.1, oma = c(5, 4, 0, 0) + 0.1,
#    xaxt = 'n', yaxt = 'n', bty = 'n')
#tpsgrid(turtle.land.adult[, , snd.min], mt, mag = 2)
#plotRefToTarget(M1 = mt, M2 = turtle.land.adult[, , snd.min])
#title(main = 'min observed')
#tpsgrid(turtle.land.adult[, , snd.max], mt, mag = 2)
#plotRefToTarget(M1 = mt, M2 = turtle.land.adult[, , snd.max])
#title(main = 'max observed')
#par(mfrow = c(1, 1))

snd.mean <- multishape.plot(list(turtle.land.adult[, , snd.min], 
                                 mt,
                                 turtle.land.adult[, , snd.max]), 
                            links = links,
                            labeller = ex.lab)
snd.mean <- snd.mean + theme(axis.title = element_blank(),
                             axis.text = element_text(size = 4))
snd.mean <- snd.mean + coord_equal()
snd.mean
@
\end{frame}


\section{Discussion}
\begin{frame}
  \frametitle{Future}

  \begin{itemize}
    \item illustration of morphological validation of previously cryptic variation
      \begin{itemize}
        \item the concordance is remarkable
        \item large sample sizes can be difficult
      \end{itemize}
    \item utility of large data, machine learning methods 
    \item unsupervised methods for when no explicit hypothesis -- nonparametric Bayes
    \item cause of interclass variation -- local adaptation? pure isolation?
  \end{itemize}

\end{frame}

\begin{frame}
  \frametitle{Acknowledgements}
  \begin{columns}
    \begin{column}{0.5\textwidth}
      \begin{itemize}
        \item Ben Frable, Dallas Krentzel, Michael Foote, David Bapst
        \item collections at CAS, FMNH, LACM, LSUMNS, MSE, MVZ, NMNH, SBMNH, SDMNH, UCMP, UMZC
        \item NSF DBI-0306158 to KDA
      \end{itemize}
    \end{column}
    \begin{column}{0.5\textwidth}
      \includegraphics[height = 0.25\textheight, keepaspectratio = true]{figure/chicago} \\
      \includegraphics[height = 0.25\textheight, width = \textwidth, keepaspectratio = true]{figure/field} \\
      \includegraphics[height = 0.25\textheight, keepaspectratio = true]{figure/csu}
    \end{column}
  \end{columns}
\end{frame}
\end{document}
